version: "3.9"

services:
  taipy:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: comfyui_inobridge
    volumes:
      - .:/app
    restart: no
    